FROM maven:3.8.4-openjdk-11
MAINTAINER bhimsur

ARG GCS_ENDPOINT
ARG GCS_SECRET
ARG GCS_ACCESS
ARG GCS_BUCKET

ENV STORAGE_GCS_ENDPOINT=$GCS_ENDPOINT
ENV STORAGE_GCS_KEY_SECRET=$GCS_SECRET
ENV STORAGE_GCS_KEY_ACCESS=$GCS_ACCESS
ENV STORAGE_GCS_BUCKET=$GCS_BUCKET

WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests
RUN cp target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]